repos/main/routes.py
from flask import Blueprint, request, jsonify, render_template, url_for, session, redirect
from sqlalchemy import or_
from flask_login import login_required, current_user
from repos.modules import Task, Document, Project
from repos.users.routes import logout

main = Blueprint('main', __name__)


@main.route('/home', methods=['POST', 'GET'])
@login_required
def home():
    if not current_user.is_authenticated or 'PROJECT_IDS' not in session:
        logout()

    company_name = current_user.project_name
    project_ids = session.get('PROJECT_IDS')
    project_filter = [Task.project_id == project_id for project_id in project_ids]
    project_id_filter = or_(*project_filter)
    if request.method == 'POST':
        draw = request.form['draw']
        row = int(request.form['start'])
        row_per_page = int(request.form['length'])
        searchValue = request.form["search[value]"]
        column_search = {}
        # if searchValue:
        #     column_search['task_id'] = searchValue
        column1_search = request.form.get('columns[0][search][value]')
        if column1_search:
            column_search['entity_name'] = column1_search
        column2_search = request.form.get('columns[1][search][value]')
        if column2_search:
            column_search['location_code'] = column2_search
        column3_search = request.form.get('columns[2][search][value]')
        if column3_search:
            column_search['type_of_licence'] = column3_search
        column4_search = request.form.get('columns[3][search][value]')
        if column4_search:
            column_search['state'] = column4_search
        column5_search = request.form.get('columns[4][search][value]')
        if column5_search:
            column_search['district'] = column5_search
        column6_search = request.form.get('columns[5][search][value]')
        if column6_search:
            column_search['locality'] = column6_search
        column7_search = request.form.get('columns[6][search][value]')
        if column7_search:
            column_search['created_time'] = column7_search
        column8_search = request.form.get('columns[7][search][value]')
        if column8_search:
            column_search['licence_expiry_date'] = column8_search
        column9_search = request.form.get('columns[8][search][value]')
        if column9_search:
            column_search['status'] = column9_search

        # total number of count without filtering
        total_task_count = Task.query.filter(project_id_filter).count()

        like_string = '%{}%'.format(searchValue)
        # with filtering query
        filter_query = Task.query.filter(project_id_filter, or_(Task.entity_name.ilike(like_string),
                                                                Task.client_status.ilike(like_string),
                                                                Task.state.ilike(like_string),
                                                                Task.district.ilike(like_string),
                                                                Task.type_of_licence.ilike(like_string),
                                                                Task.location_code.ilike(like_string),
                                                                Task.created_time.ilike(like_string),
                                                                Task.licence_expiry_date.ilike(like_string),
                                                                Task.locality.ilike(like_string)))

        # total number of count with filtering
        total_recordwith_filter_count = filter_query.count()
        filter_result = filter_query.all()

        # Column-wise filter
        or_conditions = []
        if bool(column_search):
            for column_name, column_search_value in column_search.items():
                filter_condition = getattr(Task, column_name).ilike(f'%{column_search_value}%')
                or_conditions.append(filter_condition)

            filter_column = Task.query.filter(project_id_filter, or_(*or_conditions))
            filter_column_result = filter_column.all()

        task_data = []
        if searchValue != '':
            tasks = filter_query.offset(row).limit(row_per_page).all()
            if bool(column_search):
                # Extract the attribute that you want to use for comparison, for example 'task_id'
                task_ids = [task.task_id for task in filter_result]
                filter_task_ids = [task.task_id for task in filter_column_result]

                # Find common task_ids between the two lists
                common_task_ids = list(set(task_ids) & set(filter_task_ids))

                # Filter the original lists to get the common objects
                common_tasks = [task for task in filter_result if task.task_id in common_task_ids]
                total_recordwith_filter_count = len(common_tasks)
                tasks = common_tasks[row:row + row_per_page]
        elif bool(column_search):
            tasks = filter_column.offset(row).limit(row_per_page).all()
            # Extract the attribute that you want to use for comparison, for example 'task_id'
            task_ids = [task.task_id for task in filter_result]
            filter_task_ids = [task.task_id for task in filter_column_result]

            # Find common task_ids between the two lists
            common_task_ids = list(set(task_ids) & set(filter_task_ids))

            # Filter the original lists to get the common objects
            common_tasks = [task for task in filter_result if task.task_id in common_task_ids]
            total_recordwith_filter_count = len(common_tasks)
        else:
            tasks = Task.query.filter(project_id_filter).offset(row).limit(row_per_page).all()

        for row in tasks:
            document_name = Document.query.filter(Document.task_id == row.task_id, Document.file_status == 0).all()
            project_name = Project.query.with_entities(Project.project_name).filter_by(id=row.project_id).first()[0]
            cols = ''
            if document_name:
                for doc in document_name:
                    cols += f'<div class="button-container">' + \
                            '<div class="button-group">' + \
                            f'<a href="' + url_for('static', filename='imageupload/' + project_name + '/' + str(
                        row.task_id) + '/' + doc.file_name) + '" class="btn-sm btn-smaller btn-download" ' \
                                                              'target="_blank">' + doc.file_name + '</a>' '</div>''</div>'
            else:
                cols += '<p><span style="color: orange;">Proccesing</span></p>'

            created_time = row.created_time.strftime('%d/%m/%Y') if row.created_time is not None else ''
            licence_expiry_date = row.licence_expiry_date.strftime(
                '%d/%m/%Y') if row.licence_expiry_date is not None else ''

            task_data.append({
                'document': cols,
                'task_id': f'{row.task_id}',
                'entity_name': row.entity_name,
                'status': row.client_status,
                'state': row.state,
                'district': row.district,
                'type_of_licence': row.type_of_licence,
                'location_code': row.location_code,
                'assigned_date': created_time,
                'licence_expiry_date': licence_expiry_date,
                'locality': row.locality,
            })

        response = {
            'draw': draw,
            'iTotalRecords': total_task_count,
            'iTotalDisplayRecords': total_recordwith_filter_count,
            'aaData': task_data,
        }
        return jsonify(response)
    else:
        tasks_status = Task.query.filter(project_id_filter).all()
        start = len(tasks_status)
        doc_pending, under_process, onhold, closed = 0, 0, 0, 0
        for status_value in tasks_status:
            if status_value.client_status == 'Document Pending':
                doc_pending += 1
            elif status_value.client_status == 'On Hold':
                onhold += 1
            elif status_value.client_status == 'Closed':
                closed += 1
            else:
                under_process += 1

        status_count = (
            {'start_count': start, 'doc_pending_count': doc_pending, 'under_process_count': under_process,
             'onhold_count': onhold, 'closed_count': closed})

        return render_template('home.html', status_count=status_count, project_name=company_name)


@main.route('/task_status_data', methods=['POST', 'GET'])
@login_required
def task_status_data():
    if 'PROJECT_IDS' not in session:
        return redirect(url_for('users.login'))

    company_name = current_user.project_name
    project_ids = session.get('PROJECT_IDS')
    project_filter = [Task.project_id == project_id for project_id in project_ids]
    project_id_filter = or_(*project_filter)
    if request.method == 'POST':
        filter_status = request.form["status"]
        draw = request.form['draw']
        row = int(request.form['start'])
        row_per_page = int(request.form['length'])
        searchValue = request.form["search[value]"]

        # total number of count without filtering
        client_status_condition = Task.client_status == filter_status
        total_task_count = Task.query.filter(project_id_filter, client_status_condition).count()

        like_string = '%{}%'.format(searchValue)
        # with filtering query
        if filter_status == 'assigned':
            filter_query = Task.query.filter(project_id_filter,
                                             or_(Task.entity_name.ilike(like_string),
                                                 Task.client_status.ilike(like_string),
                                                 Task.state.ilike(like_string),
                                                 Task.district.ilike(like_string),

repos/users/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash, session
from flask_login import current_user, logout_user, login_user
from repos.modules import User, Project, Log
from flask_bcrypt import Bcrypt
import datetime
from repos import db

users = Blueprint('users', __name__)


@users.route('/')
@users.route('/login', methods=['POST', 'GET'])
def login():
    bcrypt = Bcrypt()
    password = "password".encode('utf-8')
    hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
    if current_user.is_authenticated:
        if 'PROJECT_IDS' not in session:
            logout()
    if request.method == "POST":
        data = request.form
        user = User.query.filter_by(useremail=data['user_email']).first()
        password = data['user_password']
        if user and bcrypt.check_password_hash(user.password, password):
            login_user(user, remember='True')
            next_page = request.args.get('next')
            project_id = Project.query.with_entities(Project.id).filter_by(parent_project_name=user.project_name).all()
            project_ids = [item[0] for item in project_id]
            session['PROJECT_IDS'] = project_ids
            session['COMPANY_NAME'] =  user.project_name
            flash('You have been loggen in!', 'success')
            message = f'Logged in to Traxx- user id {user.id}'
            log_info = Log(action=message, table_name='user', user_id=current_user.id,
                           action_time=datetime.datetime.now())
            db.session.add(log_info)
            db.session.commit()
            if user.project_name == 'AAVANA':
                return redirect(next_page) if next_page else redirect(url_for('aavana.aavana_home'))
            else:
                return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash("Login Unsuccessful. Please try with correct email and password", 'danger')
    return render_template('login.html')


@users.route('/logout')
def logout():
    message = f'Logged out from Traxx- user id {current_user.id}'
    log_info = Log(action=message, table_name='user', user_id=current_user.id,
                   action_time=datetime.datetime.now())
    db.session.add(log_info)
    db.session.commit()
    db.session.close()
    logout_user()
    session.pop('PROJECT_IDS', None)
    session.pop('COMPANY_NAME', None)
    return redirect(url_for('users.login'))

repos/templates/home.html
{% extends "layout.html" %}
{% block content %}
<style>
    /* Custom gradient background */
    .gradient-bg {
        background: linear-gradient(45deg, #FF5733, #6D4C41); /* Adjust colors as needed */
        color: white; /* Text color for better visibility */
    }
    .blurred {
        filter: blur(2px); /* Adjust the blur amount as needed */
    }
</style>
<body class="d-flex flex-column h-100">
    <section class="bg-light bg-gradient p-md-1" id="verification">
        <div class="container py-4">
            <!--<div class="row gx-5 justify-content-center">
                <div class="col-lg-8 col-xl-7">
                    <div class="text-center">
                        <h2 class="fw-bolder text-primary">{{ project_name }}</h2>
                    </div>
                </div>
            </div>-->
            <div class="row d-flex justify-content-center">
                <div class="col">
                    <a id="start_task" data-task_name="assigned" href="#" class="text-decoration-none text-dark">
                        <div class="card h-100 shadow-sm border-0 bg-warning">
                            <div class="card-body d-flex flex-column justify-content-center align-items-center p-4 text-center">
                                <h5 class="card-title">Assigned</h5>
                                <h5 class="card-title">{{status_count.start_count}}</h5>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-auto d-flex align-items-center">
                    <span style="font-size: 20px;">=</span>
                </div>
                <div class="col">
                    <a id="document_pen_task" data-task_name="Document Pending" href="#" class="text-decoration-none text-dark">
                        <div class="card h-100 shadow-sm border-0 bg-secondary text-white">
                            <div class="card-body d-flex flex-column justify-content-center align-items-center p-4 text-center">
                                <h5 class="card-title">Document Pending</h5>
                                <h5 class="card-title">{{status_count.doc_pending_count}}</h5>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col">
                    <a id="under_process_task" data-task_name="Under Process" href="#" class="text-decoration-none text-dark">
                        <div class="card h-100 shadow-sm border-0 bg-info text-white">
                            <div class="card-body d-flex flex-column justify-content-center align-items-center p-4 text-center">
                                <h5 class="card-title">Under Process</h5>
                                <h5 class="card-title">{{status_count.under_process_count}}</h5>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col">
                    <a id="onhold_task" data-task_name="On Hold" href="#" class="text-decoration-none text-dark">
                        <div class="card h-100 shadow-sm border-0 gradient-bg">
                            <div class="card-body d-flex flex-column justify-content-center align-items-center p-4 text-center">
                                <h5 class="card-title">On Hold</h5>
                                <h5 class="card-title">{{ status_count.onhold_count }}</h5>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col">
                    <a id="closed_task" data-task_name="Closed" href="#" class="text-decoration-none text-dark">
                        <div class="card h-100 shadow-sm border-0 bg-success text-white">
                            <div class="card-body d-flex flex-column justify-content-center align-items-center p-4 text-center">
                                <h5 class="card-title">Closed</h5>
                                <h5 class="card-title">{{ status_count.closed_count }}</h5>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="table-responsive">
            <table id="taskTable" class="display table table-striped table-bordered table-hover" style="width:100%">
                <thead>
                    <tr class="table-primary">
                        <th>Entity Name</th>
                        <th>Location Code</th>
                        <th>Type of Licence</th>
                        <th>State</th>
                        <th>District</th>
                        <th>Locality</th>
                        <th>Assigned Date</th>
                        <th>licence Expiry Date</th>
                        <th>Status</th>
                        <th>Documents</th>
                    </tr>
                </thead>
            </table>
        </div>
    </section>
</body>
<script>
    $(document).ready(function (){
        loadDatatableAjax();

        function loadDatatableAjax(){
            var taskDatatable = $('#taskTable').DataTable({
                dom: 'B<"top"lf>t<"bottom"ip><"clear">', // Custom positioning
                buttons: [
                    'csv', 'excel'
                ],
                'processing': true,
                'serverSide': true,
                'serverMethod': 'post',
                'ajax': {
                    'url':'/home'
                },
                lengthMenu: [10, 25, 50, 100], // Specify the options for number of records per page
                pageLength: 10,
                searching: true,
                sort: false,
                "serverSide": true,
                'columns': [
                        { data: 'entity_name'},
                        { data: 'location_code'},
                        { data: 'type_of_licence'},
                        { data: 'state'},
                        { data: 'district'},
                        { data: 'locality'},
                        { data: 'assigned_date'},
                        { data: 'licence_expiry_date'},
                        { data: 'status'},
                        { data: 'document'},
                    ]
            });
            // Create search inputs for each column
            taskDatatable.columns().every(function() {
                var column = this;
                var headerText = $(column.header()).text().trim();
                if(headerText != "Documents") {
                    var input = $('<input type="text" placeholder="Search ' + headerText + '">')
                        .appendTo($(column.header()))
                        .on('keyup change', function () {
                            column.search(this.value).draw();
                        });
                }
            });
        }


        $('#start_task, #under_process_task, #onhold_task, #closed_task, #document_pen_task').click(function(event) {
            if ($(this).hasClass("blurred")) {
                $(this).removeClass("blurred");
                $('#taskTable').dataTable().fnDestroy();
                var taskDatatable = $('#taskTable').DataTable({
                    dom: 'B<"top"lf>t<"bottom"ip><"clear">', // Custom positioning
                    buttons: [
                        'csv', 'excel'
                    ],
                    'processing': true,
                    'serverSide': true,
                    'serverMethod': 'post',
                    'ajax': {
                        url: "{{ url_for('main.home')}}",
                        dataType: 'JSON',
                        method: 'POST',
                        data: {'status': task_status}
                    },
                    'lengthMenu': [10, 25, 50, 100],
                    searching: true,
                    sort: false,
                    "serverSide": true,
                    'columns': [
                            { data: 'entity_name'},
                            { data: 'location_code'},
                            { data: 'type_of_licence'},
                            { data: 'state'},
                            { data: 'district'},
                            { data: 'locality'},
                            { data: 'assigned_date'},
                            { data: 'licence_expiry_date'},
                            { data: 'status'},
                            { data: 'document'},
                        ]
                });
            }else{
                $(".text-dark").removeClass("blurred");
                $(this).toggleClass("blurred");
                var task_status = $(this).data('task_name');
                $('#taskTable').dataTable().fnDestroy();
                var taskDatatable = $('#taskTable').DataTable({
                    dom: 'B<"top"lf>t<"bottom"ip><"clear">', // Custom positioning
                    buttons: [
                        'csv', 'excel'
                    ],
                    'processing': true,
                    'serverSide': true,
                    'serverMethod': 'post',
                    'ajax': {
                        url: "{{ url_for('main.task_status_data')}}",
                        dataType: 'JSON',
                        method: 'POST',
                        data: {'status': task_status}
                    },
                    'lengthMenu': [10, 25, 50, 100],
                    searching: true,
                    sort: false,
                    "serverSide": true,
                    'columns': [
                            { data: 'entity_name'},
                            { data: 'location_code'},
                            { data: 'type_of_licence'},
                            { data: 'state'},
                            { data: 'district'},
                            { data: 'locality'},
                            { data: 'assigned_date'},
                            { data: 'licence_expiry_date'},
                            { data: 'status'},
                            { data: 'document'},
                        ]
                });
            }
        });
    });
</script>
{% endblock content %}

repos/templates/layout.html
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Repos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.css" />
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
    <style>
        body {
            background-color: #f5f5f5;
        }

        input {
            margin-bottom: 10px;
        }

        .navbar {
            background-color: #343a40;
        }

        .navbar-brand,
        .navbar-nav .nav-link {
            color: #ffffff;
        }

        .navbar-toggler-icon {
            background-color: #ffffff;
        }

        .navbar-collapse {
            justify-content: flex-end;
        }

        .alert {
            margin-top: 20px;
        }

        footer {
            background-color: #343a40;
        }

        footer .text-white {
            color: #ffffff;
        }
        .table-responsive {
        overflow-x: auto;
        }

        /* Add more styling as needed */
    </style>
</head>

<body class="d-flex flex-column h-100">
    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark" style="background-color: #1c6dd6; /* Dark Blue color 336699 0d1eb5*/">
            <div class="container">
                <a class="navbar-brand" href="#">Traax</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
<!--                            <a class="nav-link active" aria-current="page" href="{{ url_for('aavana.aavana_home') if current_user.project_name == 'AAVANA' else url_for('main.home') }}">Home</a>-->
                        </li>
                    </ul>
                    {% if current_user.is_authenticated %}
                    <div class="nav-item mx-auto">
                        <span class="nav-link text-white" style="font-size: 1.2rem; font-weight: bold; margin: 0;">{{ session.get("COMPANY_NAME", 'fgdgd') }}</span>
                    </div>
                    {% endif %}
                    <div class="d-flex navbar-nav ml-auto align-items-center">
                        {% if current_user.is_authenticated %}
                        <span class="nav-link text-white">Next Refresh</span>
                        <div id="countdown"></div>
                        <a class="nav-link text-white ml-auto mr-0" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{{ url_for('users.login') }}">Login</a>
                        </li>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div role="main" class="container" style="display: inline-block">
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                <!-- ... your messages display ... -->
                {% endwith %}
            </div>
        </div>
    </div>
    {% block content %}
    {% endblock %}
    <footer class="footer mt-auto py-3 bg-secondary bg-gradient">
        <div class="container">
            <span class="text-white">Copyright © Aavana Corporate Solutions Private Limited 2017-2023</span>
        </div>
    </footer>
    {% if current_user.is_authenticated %}
        <script>
            // Function to calculate the time remaining until 11:00 AM of the next day
        function calculateTimeRemaining() {
            const currentDate = new Date();
            const targetDate = new Date(currentDate);
            targetDate.setHours(11, 0, 0, 0); // Set the target time to 11:00 AM
            if (currentDate >= targetDate) {
                targetDate.setDate(targetDate.getDate() + 1);
            }
            return targetDate - currentDate;
        }

        // Update the countdown every second
        const countdown = document.getElementById('countdown');
        function updateCountdown() {
            const timeRemaining = calculateTimeRemaining();

            if (timeRemaining <= 0) {
                // Calculate the target date for 11:00 AM of the next day
                const nextDay = new Date();
                nextDay.setHours(11, 0, 0, 0);
                nextDay.setDate(nextDay.getDate() + 1);

                countdown.innerHTML = "Countdown expired!";
                setTimeout(updateCountdown, nextDay - new Date()); // Reset at 11:00 AM next day
            } else {
                const hours = Math.floor(timeRemaining / (1000 * 60 * 60));
                const minutes = Math.floor((timeRemaining % (1000 * 60 * 60)) / (1000 * 60));
                const seconds = Math.floor((timeRemaining % (1000 * 60)) / 1000);

                countdown.innerHTML = `${hours}h ${minutes}m ${seconds}s`;
                setTimeout(updateCountdown, 1000); // Update every 1 second
            }
        }

        // Initial call to set up the countdown
        updateCountdown();
        </script>
    {% endif %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!--Datatble library-->
    <link href='https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <!-- Include the DataTables Buttons CSS and JS files -->
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.7.1/css/buttons.dataTables.min.css">
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/vfs_fonts.js"></script>
</body>

</html>